package Clases;
// Generated 30-sep-2014 16:43:33 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Actor generated by hbm2java
 */
public class Actor  implements java.io.Serializable {


     private Integer acId;
     private String acNombre;
     private Set elencos = new HashSet(0);

    public Actor() {
    }

    public Actor(String acNombre, Set elencos) {
       this.acNombre = acNombre;
       this.elencos = elencos;
    }
   
    public Integer getAcId() {
        return this.acId;
    }
    
    public void setAcId(Integer acId) {
        this.acId = acId;
    }
    public String getAcNombre() {
        return this.acNombre;
    }
    
    public void setAcNombre(String acNombre) {
        this.acNombre = acNombre;
    }
    public Set getElencos() {
        return this.elencos;
    }
    
    public void setElencos(Set elencos) {
        this.elencos = elencos;
    }




}


