package Clases;
// Generated 30-sep-2014 16:43:33 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Cine generated by hbm2java
 */
public class Cine  implements java.io.Serializable {


     private Integer cnId;
     private Ciudad ciudad;
     private String cnNombre;
     private Set estrenos = new HashSet(0);

    public Cine() {
    }

	
    public Cine(Ciudad ciudad) {
        this.ciudad = ciudad;
    }
    public Cine(Ciudad ciudad, String cnNombre, Set estrenos) {
       this.ciudad = ciudad;
       this.cnNombre = cnNombre;
       this.estrenos = estrenos;
    }
   
    public Integer getCnId() {
        return this.cnId;
    }
    
    public void setCnId(Integer cnId) {
        this.cnId = cnId;
    }
    public Ciudad getCiudad() {
        return this.ciudad;
    }
    
    public void setCiudad(Ciudad ciudad) {
        this.ciudad = ciudad;
    }
    public String getCnNombre() {
        return this.cnNombre;
    }
    
    public void setCnNombre(String cnNombre) {
        this.cnNombre = cnNombre;
    }
    public Set getEstrenos() {
        return this.estrenos;
    }
    
    public void setEstrenos(Set estrenos) {
        this.estrenos = estrenos;
    }




}


