package Clases;
// Generated 30-sep-2014 16:43:33 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Ciudad generated by hbm2java
 */
public class Ciudad  implements java.io.Serializable {


     private Integer cdId;
     private String cdNombre;
     private Integer cdRegion;
     private Set cines = new HashSet(0);

    public Ciudad() {
    }

    public Ciudad(String cdNombre, Integer cdRegion, Set cines) {
       this.cdNombre = cdNombre;
       this.cdRegion = cdRegion;
       this.cines = cines;
    }
   
    public Integer getCdId() {
        return this.cdId;
    }
    
    public void setCdId(Integer cdId) {
        this.cdId = cdId;
    }
    public String getCdNombre() {
        return this.cdNombre;
    }
    
    public void setCdNombre(String cdNombre) {
        this.cdNombre = cdNombre;
    }
    public Integer getCdRegion() {
        return this.cdRegion;
    }
    
    public void setCdRegion(Integer cdRegion) {
        this.cdRegion = cdRegion;
    }
    public Set getCines() {
        return this.cines;
    }
    
    public void setCines(Set cines) {
        this.cines = cines;
    }




}


