package Clases;
// Generated 30-sep-2014 16:43:33 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Director generated by hbm2java
 */
public class Director  implements java.io.Serializable {


     private Integer drId;
     private String drNombre;
     private Integer drEdad;
     private Set peliculas = new HashSet(0);

    public Director() {
    }

    public Director(String drNombre, Integer drEdad, Set peliculas) {
       this.drNombre = drNombre;
       this.drEdad = drEdad;
       this.peliculas = peliculas;
    }
   
    public Integer getDrId() {
        return this.drId;
    }
    
    public void setDrId(Integer drId) {
        this.drId = drId;
    }
    public String getDrNombre() {
        return this.drNombre;
    }
    
    public void setDrNombre(String drNombre) {
        this.drNombre = drNombre;
    }
    public Integer getDrEdad() {
        return this.drEdad;
    }
    
    public void setDrEdad(Integer drEdad) {
        this.drEdad = drEdad;
    }
    public Set getPeliculas() {
        return this.peliculas;
    }
    
    public void setPeliculas(Set peliculas) {
        this.peliculas = peliculas;
    }




}


