package Clases;
// Generated 30-sep-2014 16:43:33 by Hibernate Tools 3.6.0



/**
 * ElencoId generated by hbm2java
 */
public class ElencoId  implements java.io.Serializable {


     private int actorAcId;
     private int peliculaPlId;

    public ElencoId() {
    }

    public ElencoId(int actorAcId, int peliculaPlId) {
       this.actorAcId = actorAcId;
       this.peliculaPlId = peliculaPlId;
    }
   
    public int getActorAcId() {
        return this.actorAcId;
    }
    
    public void setActorAcId(int actorAcId) {
        this.actorAcId = actorAcId;
    }
    public int getPeliculaPlId() {
        return this.peliculaPlId;
    }
    
    public void setPeliculaPlId(int peliculaPlId) {
        this.peliculaPlId = peliculaPlId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ElencoId) ) return false;
		 ElencoId castOther = ( ElencoId ) other; 
         
		 return (this.getActorAcId()==castOther.getActorAcId())
 && (this.getPeliculaPlId()==castOther.getPeliculaPlId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getActorAcId();
         result = 37 * result + this.getPeliculaPlId();
         return result;
   }   


}


