package Clases;
// Generated 30-sep-2014 16:43:33 by Hibernate Tools 3.6.0



/**
 * EstrenoId generated by hbm2java
 */
public class EstrenoId  implements java.io.Serializable {


     private int peliculaPlId;
     private int cineCnId;

    public EstrenoId() {
    }

    public EstrenoId(int peliculaPlId, int cineCnId) {
       this.peliculaPlId = peliculaPlId;
       this.cineCnId = cineCnId;
    }
   
    public int getPeliculaPlId() {
        return this.peliculaPlId;
    }
    
    public void setPeliculaPlId(int peliculaPlId) {
        this.peliculaPlId = peliculaPlId;
    }
    public int getCineCnId() {
        return this.cineCnId;
    }
    
    public void setCineCnId(int cineCnId) {
        this.cineCnId = cineCnId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof EstrenoId) ) return false;
		 EstrenoId castOther = ( EstrenoId ) other; 
         
		 return (this.getPeliculaPlId()==castOther.getPeliculaPlId())
 && (this.getCineCnId()==castOther.getCineCnId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getPeliculaPlId();
         result = 37 * result + this.getCineCnId();
         return result;
   }   


}


